### ISSUE TITLE
Getting error when trying to run sync_motors

### ISSUE THREAD

**Issue by erlis** [MRX8024/motors-sync#14]
I'm getting this error when I'm running SYNC_MOTORS 

![image](https://github.com/user-attachments/assets/1a86499e-46b5-4dfb-8750-9a59ff2200fe)

it looks like the steppers array is missing, this is weird, 

```
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 298, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/gcode.py", line 207, in func
    return origfunc(self._get_extended_params(params))
  File "/home/pi/klipper/klippy/extras/motors_sync.py", line 517, in cmd_RUN_SYNC
    init_magnitude = self._measure(axis, True)
  File "/home/pi/klipper/klippy/extras/motors_sync.py", line 309, in _measure
    if buzz: self._buzz(axis)
  File "/home/pi/klipper/klippy/extras/motors_sync.py", line 277, in _buzz
    lookup_sec_stepper = self.motion[axis]['lookuped_steppers'][1]
IndexError: list index out of range
Transition to shutdown state: Internal error on command:"SYNC_MOTORS"
```

**Comment by erlis** [comment]
disregard, I just realized I had the two other motors commented out in my config file, and that is the reason it was not found...

**Comment by MRX8024** [comment]
This is a good reason to add protection against such cases. 
Thanks, you are welcome.
